// src/routes/bday25/+page.svelte
<div>
    <a
        style="position: absolute; top: 8px; left: 16px"
        href="https://saleh.sh"
    >
        &lt;-back
    </a>
    <br />
    <h2>Invitation to celebrate my birthday (2025)</h2>
    <img width="200" height="auto" rel="preload" src="/assets/bday25_moi.jpg" alt="" />

    <br />
    <br />
    Friends, familiares, familia, welcome to another one of my (some would say stupid, i would say creative) ideas
    <br />
    <br />
    As you might know, I was born around this general time of year many years ago. And I want to participate in the festivities that people usually partake in when this time of year comes
    <br />
    <br />
    So, I thought why not celebrate like them. And so ... I'm gonna celebrate by running from NJ (thru NY) to CT. A tri-state run
    <br />
    <br />

    <img width="800" height="auto" rel="preload" src="/assets/bday25_route.jpeg" alt="" />
    <br />
    <br />
    I'm not sure what the total mileage will be, but I think it should be close to ~24-28 miles 😨
    <br />
    <br />
    The general route is Fort Lee, NJ -> (thru GWB) Manhattan -> Then roughly follow the East Coast Greenway from The Bronx -> Westchester -> Greenwich, CT
    Then come back home on the Metro North
    <br />
    <br />
    I'm gonna do it this Sunday, July 13th. And start at 7am from Fort Lee, NJ
    <br />
    <br />
    Now you might be wondering, how can I help you celebrate?
    <br />
    <br />
    Well ... I think this will be a very miserable experience. But if you want to join me (in spirit), you can add songs to this <a
        href="https://open.spotify.com/playlist/2WFFJGE3XG2rp29MqHM9wr?si=ee8573c051864aec&pt=5a1b2e5e37a94e77b1b3eb0885052cca"
        >Spotify playlist.</a
    > but please keep it ~5 songs, if you don't have Spotify, send me the song(s) and I can add it to the playlist
    <br />
    <br />
    If you want to join me (in person), you can also do so, but I just want you to imagine the level or pain and misery it will be before you commit haha
    <br />
    You can follow my Whatsapp channel for updates: <a href="https://whatsapp.com/channel/0029Vb5vbXGDp2Q1XkxBi50p">https://whatsapp.com/channel/0029Vb5vbXGDp2Q1XkxBi50p</a>
    <br />
    You can also follow me on <a href="https://www.strava.com/athletes/52586093">Strava</a>
    <br />
    <br />
    Ultimately, you are seeing this page because you are very (very) near and dear to my heart and I want to thank you for your beautiful presence in my life ❤️
    <br />
    And in case I haven't told you lately, I love you and I honestly don't know where I would be without you in my life.
    <br />
    <br />
</div>

<style lang="scss">
    div,
    h2,
    a {
        font-family: 'Roboto', Arial, sans-serif;
        font-size: 1.1em;
    }

    img {
        max-width: 100%;
        height: auto;
    }

    // Override global.scss's `* { white-space: pre-wrap }`. Vue 2's
    // template compiler stripped inter-element whitespace; Svelte
    // preserves it, which inflates page height when combined with the
    // global pre-wrap rule.
    div {
        white-space: normal;
    }
</style>

// src/components/Bday25.vue
<template>
    <div>
        <a
            style="position: absolute; top: 8px; left: 16px"
            href="https://saleh.sh"
        >
            &lt;-back
        </a>
        <br />
        <h2>Invitation to celebrate my birthday (2025)</h2>
        <img
            width="200px"
            height="auto"
            rel="preload"
            src="/assets/bday25_moi.jpg"
        />

        <br />
        <br />
        Friends, familiares, familia, welcome to another one of my (some would say stupid, i would say creative) ideas
        <br />
        <br />
        As you might know, I was born around this general time of year many years ago. And I want to participate in the festivities that people usually partake in when this time of year comes
        <br />
        <br />
        So, I thought why not celebrate like them. And so ... I'm gonna celebrate by running from NJ (thru NY) to CT. A tri-state run
        <br />
        <br />
        
        <img
            width="800px"
            height="auto"
            rel="preload"
            src="/assets/bday25_route.jpeg"
        />
        <br />
        <br />
        I'm not sure what the total mileage will be, but I think it should be close to ~24-28 miles 😨
        <br />
        <br />
        The general route is Fort Lee, NJ -> (thru GWB) Manhattan -> Then roughly follow the East Coast Greenway from The Bronx -> Westchester -> Greenwich, CT
        Then come back home on the Metro North
        <br />
        <br />
        I'm gonna do it this Sunday, July 13th. And start at 7am from Fort Lee, NJ
        <br />
        <br />
        Now you might be wondering, how can I help you celebrate?
        <br />
        <br />
        Well ... I think this will be a very miserable experience. But if you want to join me (in spirit), you can add songs to this <a
            href="https://open.spotify.com/playlist/2WFFJGE3XG2rp29MqHM9wr?si=ee8573c051864aec&pt=5a1b2e5e37a94e77b1b3eb0885052cca"
            >Spotify playlist.</a
        > but please keep it ~5 songs, if you don't have Spotify, send me the song(s) and I can add it to the playlist
        <br />
        <br />
        If you want to join me (in person), you can also do so, but I just want you to imagine the level or pain and misery it will be before you commit haha
        <br />
        You can follow my Whatsapp channel for updates: <a href="https://whatsapp.com/channel/0029Vb5vbXGDp2Q1XkxBi50p">https://whatsapp.com/channel/0029Vb5vbXGDp2Q1XkxBi50p</a> 
        <br/>
        You can also follow me on <a href="https://www.strava.com/athletes/52586093">Strava</a>
        <br />
        <br />
        Ultimately, you are seeing this page because you are very (very) near and dear to my heart and I want to thank you for your beautiful presence in my life ❤️
        <br />
        And in case I haven't told you lately, I love you and I honestly don't know where I would be without you in my life.
        <br />
        <br />
    </div>
</template>

<script>
export default {
    name: 'Bday25',
};
</script>

<style scoped lang="scss">
div,
h2,
h3,
h4,
p,
a,
b {
    font-family: 'Roboto', Arial, sans-serif;
    font-size: 1.1em;
}
img,
.container {
    max-width: 100%;
    height: auto;
}
</style>
