// src/lib/components/Home.svelte
<script>
    import {_} from 'svelte-i18n';
    import {onMount} from 'svelte';
    import {state as appState} from '$lib/stores/state.js';
    import Icon from './Icon.svelte';
    import Icons from './Icons.svelte';
    import LangSwitcher from './LangSwitcher.svelte';
    import ThemeToggler from './ThemeToggler.svelte';

    const gitHash = GIT_DESCRIBE.hash;
    const gitLink = 'https://github.com/qirh/sala_v2/commit/' + gitHash;

    let buildTime = new Date().toISOString();
    let animationClass = '';
    let animationTimeout;
    let previousLangCode;

    $: currentLang = $appState.currentLang;
    $: localeCode = currentLang?.code ?? 'en';
    $: date = getDate(localeCode === 'ar' ? 'ar-EG' : localeCode);
    $: dateSpecial = localeCode === 'ar' ? getDate('ar-SA') : null;

    function getDate(locale) {
        return new Intl.DateTimeFormat(locale, {
            month: 'long',
            year: 'numeric',
        }).format(new Date(buildTime));
    }

    function animateLangChange(nextLang) {
        if (!nextLang || nextLang.code === previousLangCode) {
            return;
        }

        previousLangCode = nextLang.code;
        animationClass =
            nextLang.direction === 'ltr'
                ? 'section-anim-ltr'
                : 'section-anim-rtl';
        clearTimeout(animationTimeout);
        animationTimeout = setTimeout(() => {
            animationClass = '';
        }, 500);
    }

    onMount(() => {
        const htmlBuildTime =
            document.documentElement.dataset.buildTimestampUtc;
        if (htmlBuildTime) {
            buildTime = htmlBuildTime;
        }

        const unsubscribe = appState.subscribe((s) =>
            animateLangChange(s.currentLang),
        );

        return () => {
            clearTimeout(animationTimeout);
            unsubscribe();
        };
    });
</script>

<div class="grid">
    <div class="grid-langs-theme">
        <LangSwitcher class="grid-langs" />
        <ThemeToggler class="grid-theme" />
    </div>
    <div class="grid-icons">
        <Icons />
    </div>
    <div
        id="grid-main"
        class:right-to-left={currentLang?.direction === 'rtl'}
        class:section-anim-ltr={animationClass === 'section-anim-ltr'}
        class:section-anim-rtl={animationClass === 'section-anim-rtl'}
    >
        <div class="grid-title">
            <p class="main-title">{@html $_('title')}</p>
        </div>
        <div class="grid-paragraphs">
            <p>{$_('p1')}</p>
            <p>
                {$_('p2_before_smile')}<Icon icon={['far', 'smile']} />
            </p>
            <p>{$_('p3')}</p>
            <p>{$_('p4')}</p>
            <p>{$_('p5')}</p>
        </div>
        <div class="grid-picture">
            <img
                class="picture"
                alt="Saleh in running gear"
                rel="preload"
                title={$_('pictureTitle')}
                src="/assets/moi.jpg"
            />
        </div>
    </div>
    <div class="grid-footer">
        <p>
            {$_('footerLastUpdated')}
            <a href={gitLink}
                >{date}{#if dateSpecial}~~{dateSpecial}{/if}</a
            >
        </p>
    </div>
</div>

// src/components/Home.vue
<template>
    <div class="grid">
        <div class="grid-langs-theme">
            <LangSwitcher class="grid-langs"></LangSwitcher>
            <ThemeToggler class="grid-theme"></ThemeToggler>
        </div>
        <div class="grid-icons">
            <Icons></Icons>
        </div>
        <div id="grid-main" :class="[{'right-to-left': isRTL}, animClass]">
            <div class="grid-title">
                <p class="main-title" v-html="$t('title')"></p>
            </div>
            <div class="grid-paragraphs">
                <!-- eslint-disable -->
                <i18n-t keypath="p1" tag="p"></i18n-t>
                <i18n-t keypath="p2" tag="p">
                    <template #smile>
                        <font-awesome-icon
                            :icon="['far', 'smile']"
                        ></font-awesome-icon>
                    </template>
                </i18n-t>
                <i18n-t keypath="p3" tag="p"></i18n-t>
                <i18n-t keypath="p4" tag="p"></i18n-t>
                <i18n-t keypath="p5" tag="p"></i18n-t>
            </div>
            <div class="grid-picture">
                <img
                    class="picture"
                    alt="picture of me"
                    rel="preload"
                    :title="$t('pictureTitle')"
                    src="/assets/moi.jpg"
                />
            </div>
        </div>
        <div class="grid-footer">
            <p>
                {{ $t('footerLastUpdated') }}
                <a :href="gitLink"
                    >{{ this.date
                    }}<span v-if="this.dateSpecial"
                        >~~{{ this.dateSpecial }}</span
                    ></a
                >
            </p>
            <!-- eslint-enable -->
        </div>
    </div>
</template>

<script>
import Icons from '@/components/Icons';
import ThemeToggler from '@/components/ThemeToggler';
import LangSwitcher from '@/components/LangSwitcher';
import store from '@/store';

export default {
    name: 'Home',
    props: ['buildTime', 'gitHash'],
    data: function () {
        return {
            gitLink: 'https://github.com/qirh/sala_v2/commit/' + this.gitHash,
            animClass: '',
        };
    },
    computed: {
        date() {
            let locale = this.$i18n.locale;
            if (locale === 'ar') {
                locale = 'ar-EG';
            }
            return this.getDate(locale);
        },
        dateSpecial() {
            // get hijri date if arabic
            if (this.$i18n.locale !== 'ar') {
                return null;
            }
            let locale = 'ar-SA';
            return this.getDate(locale);
        },
        currentLangCode() {
            return store.state.currentLang ? store.state.currentLang.code : '';
        },
        isRTL() {
            return store.state.currentLang?.direction === 'rtl';
        },
    },
    components: {
        Icons,
        ThemeToggler,
        LangSwitcher,
    },
    methods: {
        getDate(locale) {
            return new Intl.DateTimeFormat(locale, {
                month: 'long',
                year: 'numeric',
            }).format(new Date(this.buildTime));
        },
        animateLangSwitch() {
            this.animClass =
                store.state.currentLang.direction === 'ltr'
                    ? 'section-anim-ltr'
                    : 'section-anim-rtl';
            setTimeout(() => {
                this.animClass = '';
            }, 500);
        },
    },
    created() {
        store.watch(
            () => {
                return this.$store.state.currentLang;
            },
            () => {
                this.animateLangSwitch();
            },
        );
    },
};
</script>
<style scoped lang="scss">
@import '../assets/styles/home.scss';
</style>
