// src/routes/nycmarathon25/+page.svelte
<div>
    <a
        style="position: absolute; top: 8px; left: 16px"
        href="https://saleh.sh"
    >
        &lt;-back
    </a>
    <br />
    <h1>Letter to Shareholders re: 2nd annual Invitation to see me run the NYC marathon</h1>
    <b>Written by Saleh Alghusson. Oct 30, 2025. 5 min read.</b>
    <br />
    <h3>To our dear shareowners:</h3>
    <br />
    Thanks for being part of the Saleh Inc. journey. It's been exciting so far.
    <br />
    <br />
    In last years letter to shareholders (that I forgot to send). I talked about my hope to reinvent what it means to run a <i>fast</i> Marathon. I noted that I have grown from not being able to walk 33 years ago to hoping to finish my first marathon. I wrote that this was just the beginning for Saleh Inc.
    <br />
    <br />
    We’ve come a long way since then, and we are working harder than ever to serve and delight CUSTOMERS. Last year, we ran a <b>VERY</b> <i>slow</i> marathon due to lack of training and preparedness.
    <br />
    <br />
    HOWEVER! Past marathon performance is not indicative of future results. This year, we will run a <b>VERY</b> <i>fast</i> marathon, because we have followed a <b>VERY</b> intense (HIIT) 12 week training plan:
    <br />
    <h3>Week 1 -- personal record for that session</h3>
    <img width="300" height="auto" rel="preload" src="/assets/training_1.jpeg" alt="" />

    <h3>a quick highlight of Weeks 2-9</h3>
    <img width="600" height="auto" rel="preload" src="/assets/training_2.jpg" alt="" />

    <h3>Week 10 -- despite challenging market conditions, we made it out of bed that day</h3>
    <img width="300" height="auto" rel="preload" src="/assets/training_3.jpeg" alt="" />
    <h3>Week 11 -- corportate retreat -- no time for training</h3>
    <br />
    <h3>Week 12 -- strategic partnership with emotional support personnel ❤️❤️❤️❤️</h3>
    <img width="300" height="auto" rel="preload" src="/assets/training_4.jpeg" alt="" />

    <h1>Logistics: how to track me</h1>
    <ul>
        <li>For maximum stakeholder visibility and transparency, I encourage all our shareholders to come out and see me in person actually running the marathon.</li>
        <li>The marathon is this Sunday. <b>Nov 2, 2025</b>.</li>
        <li>Here is the <a href="https://webassets.nyrr.org/nyrrwebsiteassets/TCSNYCM25_Map_Course_080625_M_OL.pdf" target="_blank" rel="noopener noreferrer">course map</a></li>
        <li>My bib number is <b>27769</b>.
            <ul>
                <li>You can track me using <b>find my friends</b> if you have an iphone, just lmk if you don't have me and I'll add you.</li>
                <li>Or through the tracking app from the race organizers <a href="https://www.nyrr.org/tcsnycmarathon/race-day/mobile-app" target="_blank" rel="noopener noreferrer">link</a>.</li>
            </ul>
        </li>
        <li>I am part of wave 3, which starts at 10:20am. My goal is an 8 min/mile pace, but realisticly, it will be closer to 8:30 min/mile with me getting slower the further I am in the race, you know what they say, no company is perfect.</li>
        <li>For your convenience, see Q4 Performance Metrics. i.e. a best-effort estimate of expected marathon performance</li>
    </ul>
    <br />
    <i>This document contains forward-looking statements regarding athletic performance. Actual results may vary.</i>
    <br />
    <img
        width="500"
        height="auto"
        rel="preload"
        src="/assets/nyc_marathon_25_expected_times.png"
        alt=""
    />
    <br />
    <br />
    Thank you for reading this letter, and being part of this journey, all of us at Saleh Inc appreciate your business.
    <br />
    <br />
    We have always wanted to be Earth’s Most Customer-Centric Company. We won’t change that. It’s what got us here. But I am committing us to an addition. We are going to be Earth’s Best Employer and Earth’s Safest Place to Work.
    <br />
    <br />
    Sincerely, Saleh, Chief Running Officer
    <br />
    <br />
</div>

<style lang="scss">
    :global(body) {
        background-color: rgb(255, 255, 255);
    }

    div,
    h3,
    a,
    b {
        font-family: 'Roboto', Arial, sans-serif;
        font-size: 1.1em;
    }

    img {
        max-width: 100%;
        height: auto;
    }

    // Override global.scss's `* { white-space: pre-wrap }`. Vue 2's
    // template compiler stripped inter-element whitespace; Svelte
    // preserves it, which inflates page height when combined with the
    // global pre-wrap rule.
    div {
        white-space: normal;
    }
</style>

// src/components/NYCMarathon25.vue
<template>
    <div>
        <a
            style="position: absolute; top: 8px; left: 16px"
            href="https://saleh.sh"
        >
            &lt;-back
        </a>
        <br />
        <h1>Letter to Shareholders re: 2nd annual Invitation to see me run the NYC marathon</h1>
        <b>Written by Saleh Alghusson. Oct 30, 2025. 5 min read.</b>
        <br />
        <h3>To our dear shareowners:</h3>
        <br />
        Thanks for being part of the Saleh Inc. journey. It's been exciting so far.
        <br />
        <br />
        In last years letter to shareholders (that I forgot to send). I talked about my hope to reinvent what it means to run a <i>fast</i> Marathon. I noted that I have grown from not being able to walk 33 years ago to hoping to finish my first marathon. I wrote that this was just the beginning for Saleh Inc.
        <br />
        <br />
        We’ve come a long way since then, and we are working harder than ever to serve and delight CUSTOMERS. Last year, we ran a <b>VERY</b> <i>slow</i> marathon due to lack of training and preparedness.
        <br />
        <br />
        HOWEVER! Past marathon performance is not indicative of future results. This year, we will run a <b>VERY</b> <i>fast</i> marathon, because we have followed a <b>VERY</b> intense (HIIT) 12 week training plan:  
        <br />
        <h3>Week 1 -- personal record for that session</h3>
        <img
            width="300px"
            height="auto"
            rel="preload"
            src="/assets/training_1.jpeg"
        />

        <h3>a quick highlight of Weeks 2-9</h3>
        <img
            width="600px"
            height="auto"
            rel="preload"
            src="/assets/training_2.jpg"
        />

        <h3>Week 10 -- despite challenging market conditions, we made it out of bed that day</h3>
        <img
            width="300px"
            height="auto"
            rel="preload"
            src="/assets/training_3.jpeg"
        />
        <h3>Week 11 -- corportate retreat -- no time for training</h3>
        <br />
        <h3>Week 12 -- strategic partnership with emotional support personnel ❤️❤️❤️❤️</h3>
        <img
            width="300px"
            height="auto"
            rel="preload"
            src="/assets/training_4.jpeg"
        />

        

        <h1>Logistics: how to track me</h1>
        <ul>
            <li>For maximum stakeholder visibility and transparency, I encourage all our shareholders to come out and see me in person actually running the marathon.</li>
            <li>The marathon is this Sunday. <b>Nov 2, 2025</b>.</li>
            <li>Here is the <a href="https://webassets.nyrr.org/nyrrwebsiteassets/TCSNYCM25_Map_Course_080625_M_OL.pdf" target="_blank">course map</a></li>
            <li>My bib number is <b>27769</b>.
                <ul>
                    <li>You can track me using <b>find my friends</b> if you have an iphone, just lmk if you don't have me and I'll add you.</li>
                    <li>Or through the tracking app from the race organizers <a href="https://www.nyrr.org/tcsnycmarathon/race-day/mobile-app" target="_blank">link</a>.</li>
                </ul>
            </li>
            <li>I am part of wave 3, which starts at 10:20am. My goal is an 8 min/mile pace, but realisticly, it will be closer to 8:30 min/mile with me getting slower the further I am in the race, you know what they say, no company is perfect.</li>
            <li>For your convenience, see Q4 Performance Metrics. i.e. a best-effort estimate of expected marathon performance</li>
        </ul>
        <br/>
        <i>This document contains forward-looking statements regarding athletic performance. Actual results may vary.</i>
        <br/>
        <img
                width="500px"
                height="auto"
                rel="preload"
                src="/assets/nyc_marathon_25_expected_times.png"
            />
        <br/>
        <br/>
        Thank you for reading this letter, and being part of this journey, all of us at Saleh Inc appreciate your business.
        <br/>
        <br/>
        We have always wanted to be Earth’s Most Customer-Centric Company. We won’t change that. It’s what got us here. But I am committing us to an addition. We are going to be Earth’s Best Employer and Earth’s Safest Place to Work.
        <br/>
        <br/>
        Sincerely, Saleh, Chief Running Officer
        <br/>
        <br/>
    </div>
</template>

<script>
export default {
    name: 'NYCMarathon25',
};
</script>

<style scoped lang="scss">
body {
    background-color: rgb(255, 255, 255);
}

div,
h2,
h3,
h4,
p,
a,
b {
    font-family: 'Roboto', Arial, sans-serif;
    font-size: 1.1em;
}

img,
.container {
    max-width: 100%;
    height: auto;
}
</style>
