// src/components/LangSwitcher.vue
<template>
    <ul v-if="langs.length" class="langs-list">
        <li
            v-for="lang in langs"
            :key="lang.code"
            @click="changeLang(lang.code)"
            :title="lang.code"
            :disabled="$store.state.currentLang.code === lang.code"
            class="lang-item"
            :class="[
                `${lang.fonts[0]}`,
                {
                    'selected-lang':
                        $store.state.currentLang.code === lang.code,
                },
            ]"
        >
            {{ lang.name }}
        </li>
    </ul>
</template>

<script>
import {langs, getLangObjectFromCode} from '@/consts';
import store from '@/store';

export default {
    name: 'LangSwitcher',

    computed: {
        langs() {
            return langs;
        },
    },
    methods: {
        changeLang(langCode) {
            const LangObject = getLangObjectFromCode(langCode);
            store.commit('changeLang', LangObject);
        },
    },
};
</script>
<style scoped lang="scss">
@import '../assets/styles/LangSwitcher.scss';
</style>

// src/lib/components/LangSwitcher.svelte
<script>
    import {getLangObjectFromCode, langs} from '$lib/consts.js';
    import {changeLang, state as appState} from '$lib/stores/state.js';

    function selectLang(langCode) {
        changeLang(getLangObjectFromCode(langCode));
    }
</script>

{#if langs.length}
    <ul class="langs-list">
        {#each langs as lang (lang.code)}
            <li>
                <button
                    type="button"
                    onclick={() => selectLang(lang.code)}
                    title={lang.code}
                    class="lang-item {lang.fonts[0]}"
                    class:selected-lang={$appState.currentLang?.code === lang.code}
                    disabled={$appState.currentLang?.code === lang.code}
                >
                    {lang.name}
                </button>
            </li>
        {/each}
    </ul>
{/if}
